namespace TraceUtils.SourceGenerator.Infrastructure;

/// <summary>
/// Хранит статичные данные для генерации расширений (например: namespace атрибутов, string template и так далее)
/// </summary>
internal static class TelemetryGenerationConstants
{
    /// <summary>
    /// 
    /// </summary>
    public const string ActivityOperationAttributeName = "TraceUtils.ActivityOperationAttribute";

    /// <summary>
    /// 
    /// </summary>
    public const string SpanTagAttributeName = "TraceUtils.SpanTagAttribute";

    /// <summary>
    /// 
    /// </summary>
    public const string GroupedFileTemplate = """
        // <auto-generated/>
        #nullable enable

        using System;
        using System.Diagnostics;
        using System.Threading.Tasks;
        using OpenTelemetry.Trace;
        using {{ContainingNamespace}};

        namespace TraceUtils.Extensions;

        public static class {{ClassName}}TelemetryExtensions
        {
        {{Methods}}
        }
        """;

    /// <summary>
    /// 
    /// </summary>
    public const string ExtensionMethodTemplate = """
        {{signature}}
        {
            using var activity = Utils.StartActivity("{{OperationName}}", ActivityKind.{{ActivityType}});

            if (Utils.ShouldRecordData(activity))
            {
                {{InputTagBlock}}
                try
                {
                    activity?.AddEvent(new ActivityEvent("Начало события \"{{OperationName}}\""));
                    
                    {{Call}}
                    
                    {{OutputTagBlock}}                    
                    {{ReturnStatement}}
                }
                catch (Exception ex)
                {
                    activity?.SetTag("error", true);
                    activity?.SetStatus(ActivityStatusCode.Error, ex.Message);
                    activity?.SetTag("error.type", ex.GetType().FullName ?? ex.GetType().Name);
                    activity?.SetTag("error.message", ex.Message);
                    activity?.SetTag("error.stacktrace", ex.StackTrace);

                    if (ex.InnerException is not null)
                    {
                        activity?.SetTag("error.inner_type", ex.InnerException.GetType().FullName ?? ex.InnerException.GetType().Name);
                        activity?.SetTag("error.inner_message", ex.InnerException.Message);
                    }

                    activity?.AddException(ex);

                    throw;
                }
                finally
                {
                    activity?.AddEvent(new ActivityEvent("Конец события \"{{OperationName}}\""));
                }
            }
            else
            {
                {{Call}}

                {{ReturnStatement}}
            }
        }
    """;
}
