using Microsoft.CodeAnalysis;

namespace TraceUtils.SourceGenerator.Generation;

/// <summary>
/// Общие константы и форматы отображения типов для генерации телеметрических расширений.
/// </summary>
internal static class TelemetryGenerationConstants
{
    public const string TraceEventAttributeName = "TraceUtils.Attributes.TracerEventAttribute";

    public const string TracerPropertyAttributeName = "TraceUtils.Attributes.TracerPropertyAttribute";

    public const string GroupedFileTemplate = """
        // <auto-generated/>
        #nullable enable

        using System;
        using System.Diagnostics;
        using System.Threading.Tasks;
        using OpenTelemetry.Trace;
        using {{ContainingNamespace}};

        namespace TraceUtils.Extensions;

        public static class {{ClassName}}TelemetryExtensions
        {
        {{Methods}}
        }
        """;

    public const string ExtensionMethodTemplate = """
        public static {{Async}}{{ReturnType}} {{GeneratedMethodName}}{{GenericParams}}(this {{ContainingType}} instance{{ParametersWithComma}}){{GenericConstraints}}
        {
            using var activity = Utils.StartActivity("{{OperationName}}", ActivityKind.Internal);

            {{PreCallTags}}

            try
            {
                activity?.AddEvent(new ActivityEvent("Начало события {{OperationName}}"));
                {{Call}}
                {{PostCallTags}}
            }
            catch (Exception ex)
            {
                activity?.SetStatus(ActivityStatusCode.Error, ex.Message);
                activity?.AddException(ex);
                throw;
            }
            finally 
            {
                activity?.AddEvent(new ActivityEvent("Конец события {{OperationName}}"));
            }
        }
    """;

    public static readonly SymbolDisplayFormat ParameterTypeDisplayFormat =
        new(
            globalNamespaceStyle: SymbolDisplayGlobalNamespaceStyle.Omitted,
            typeQualificationStyle: SymbolDisplayTypeQualificationStyle.NameAndContainingTypesAndNamespaces,
            genericsOptions: SymbolDisplayGenericsOptions.IncludeTypeParameters,
            miscellaneousOptions:
                SymbolDisplayMiscellaneousOptions.EscapeKeywordIdentifiers |
                SymbolDisplayMiscellaneousOptions.IncludeNullableReferenceTypeModifier |
                SymbolDisplayMiscellaneousOptions.UseSpecialTypes);

    public static readonly SymbolDisplayFormat ReturnTypeDisplayFormat =
        SymbolDisplayFormat.FullyQualifiedFormat.WithMiscellaneousOptions(
            SymbolDisplayFormat.FullyQualifiedFormat.MiscellaneousOptions |
            SymbolDisplayMiscellaneousOptions.IncludeNullableReferenceTypeModifier);
}
